// Gyldige verdier for Decor8 AI sitt API (generate_designs_for_room).
// Brukes til å validere / fylle dropdowns i opplastingsskjemaet.

export const DECOR8_ROOM_TYPES = [
  "livingroom",
  "kitchen",
  "diningroom",
  "bedroom",
  "bathroom",
  "kidsroom",
  "familyroom",
  "readingnook",
  "sunroom",
  "walkincloset",
  "mudroom",
  "toyroom",
  "office",
  "foyer",
  "powderroom",
  "laundryroom",
  "gym",
  "basement",
  "garage",
  "balcony",
  "cafe",
  "homebar",
  "study_room",
  "front_porch",
  "back_porch",
  "back_patio",
  "openplan",
  "boardroom",
  "meetingroom",
  "openworkspace",
  "privateoffice",
] as const;

export type Decor8RoomType = (typeof DECOR8_ROOM_TYPES)[number];

export const DECOR8_DESIGN_STYLES = [
  "minimalist",
  "scandinavian",
  "industrial",
  "boho",
  "traditional",
  "artdeco",
  "midcenturymodern",
  "coastal",
  "tropical",
  "eclectic",
  "contemporary",
  "frenchcountry",
  "rustic",
  "shabbychic",
  "vintage",
  "country",
  "modern",
  "asian_zen",
  "hollywoodregency",
  "bauhaus",
  "mediterranean",
  "farmhouse",
  "victorian",
  "gothic",
  "moroccan",
  "southwestern",
  "transitional",
  "maximalist",
  "arabic",
  "japandi",
  "retrofuturism",
  "artnouveau",
  "urbanmodern",
  "wabi_sabi",
  "grandmillennial",
  "coastalgrandmother",
  "newtraditional",
  "cottagecore",
  "luxemodern",
  "high_tech",
  "organicmodern",
  "tuscan",
  "cabin",
  "desertmodern",
  "global",
  "industrialchic",
  "modernfarmhouse",
  "europeanclassic",
  "neotraditional",
  "warmminimalist",
] as const;

export type Decor8DesignStyle = (typeof DECOR8_DESIGN_STYLES)[number];

// Kuratert utvalg med norske visningsnavn til opplastingsskjemaet.
// Fullt utvalg av gyldige verdier ligger i listene over og brukes til validering.
export const ROOM_TYPE_OPTIONS: { value: Decor8RoomType; label: string }[] = [
  { value: "livingroom", label: "Stue" },
  { value: "kitchen", label: "Kjøkken" },
  { value: "diningroom", label: "Spisestue" },
  { value: "bedroom", label: "Soverom" },
  { value: "bathroom", label: "Bad" },
  { value: "kidsroom", label: "Barnerom" },
  { value: "office", label: "Hjemmekontor" },
  { value: "foyer", label: "Gang/entré" },
];

export const DESIGN_STYLE_OPTIONS: { value: Decor8DesignStyle; label: string }[] = [
  { value: "scandinavian", label: "Skandinavisk" },
  { value: "minimalist", label: "Minimalistisk" },
  { value: "modern", label: "Moderne" },
  { value: "traditional", label: "Klassisk" },
  { value: "industrial", label: "Industriell" },
  { value: "rustic", label: "Rustikk" },
  { value: "coastal", label: "Kyststil" },
  { value: "boho", label: "Boho" },
];
